///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsAppIcon = 'assets/icons/app_icon.png';
  static const String iconsAppleIcon = 'assets/icons/apple_icon.svg';
  static const String iconsFacebookIcon = 'assets/icons/facebook_icon.svg';
  static const String iconsGoogleIcon = 'assets/icons/google_icon.svg';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesPageViewItem1Background = 'assets/images/page_view_item1_background.svg';
  static const String imagesPageViewItem1Image = 'assets/images/page_view_item1_image.svg';
  static const String imagesPageViewItem2Background = 'assets/images/page_view_item2_background.svg';
  static const String imagesPageViewItem2Image = 'assets/images/page_view_item2_image.svg';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesSplashBottom = 'assets/images/splashBottom.svg';
  static const String iconsCheckIcon = 'assets/icons/check_icon.svg';

}
