// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--ZXAG91q4j20INyZUjBJRPhjr7IaKzM',
    appId: '1:217445990897:web:689022519c22ddd9df4450',
    messagingSenderId: '217445990897',
    projectId: 'fruits-hub-a4abc',
    authDomain: 'fruits-hub-a4abc.firebaseapp.com',
    storageBucket: 'fruits-hub-a4abc.firebasestorage.app',
    measurementId: 'G-F6Y5NR4LYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuoYBBzQ6JEjS6cXnxB2ThloSoDkUDlrM',
    appId: '1:217445990897:android:7f4e0ac298487d88df4450',
    messagingSenderId: '217445990897',
    projectId: 'fruits-hub-a4abc',
    storageBucket: 'fruits-hub-a4abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJLNzQIRe2IJbII_I1normPwY9LQ_XPk',
    appId: '1:217445990897:ios:a18359bf425e4a10df4450',
    messagingSenderId: '217445990897',
    projectId: 'fruits-hub-a4abc',
    storageBucket: 'fruits-hub-a4abc.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJLNzQIRe2IJbII_I1normPwY9LQ_XPk',
    appId: '1:217445990897:ios:a18359bf425e4a10df4450',
    messagingSenderId: '217445990897',
    projectId: 'fruits-hub-a4abc',
    storageBucket: 'fruits-hub-a4abc.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC--ZXAG91q4j20INyZUjBJRPhjr7IaKzM',
    appId: '1:217445990897:web:3fe0ca9072ebdd73df4450',
    messagingSenderId: '217445990897',
    projectId: 'fruits-hub-a4abc',
    authDomain: 'fruits-hub-a4abc.firebaseapp.com',
    storageBucket: 'fruits-hub-a4abc.firebasestorage.app',
    measurementId: 'G-03PG6ST3QR',
  );
}
